version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: servicity
      POSTGRES_USER: aniket
      POSTGRES_PASSWORD: Anikethaldar@123
    ports:
      - "54322:5432"
    volumes:
      - servicity_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  servicity_pgdata: